name: Automated Tests

on:
    push:
        branches:
            - main
            - gh-pages
            - validation-testing

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  pip install requests
                  pip install pytest

            - name: Run tests
              run: |
                  # Create directory for test results
                  mkdir -p test_results

                  # Run pytest and save the result status
                  pytest tests/ --junitxml=test_results/results.xml -v
                  test_result=$?

                  # Save test result status to a file
                  echo "$test_result" > test_results/test_passed_flag.txt

                  # Print result based on test status
                  if [ "$test_result" -eq 0 ]; then
                      echo "All tests passed."
                  else
                      echo "Some tests failed."
                  fi
              shell: bash
