name: Index Page Automated Content Tests

on:
    push:
        branches:
            - main
            - gh-pages
            - validation-testing
            - live
            - validation-and-automation-testing

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  pip install requests
                  pip install selenium
                  pip install unittest-xml-reporting
                  pip install pytest-playwright
                  playwright install

            - name: Run tests with pytest-playwright
              run: |
                  echo "Running tests in $(pwd)/tests with pattern test*.py"
                  pytest tests --maxfail=1 --disable-warnings -q > result.log || true
                  tail -n 10 result.log
              shell: bash

            - name: Upload test results
              uses: actions/upload-artifact@v2
              with:
                  name: test-results
                  path: result.log