name: Cancel Deployment

on:
    workflow_run:
        workflows: ["Automated Tests", "W3C HTML & CSS Validation"]
        types:
            - completed
            

jobs:
    cancel_deployment:
        runs-on: ubuntu-latest

        steps:
            - name: Upload validation results
              uses: actions/upload-artifact@v3
              with:
                  name: w3c-validation-results
                  path: validation_results/

            - name: Cancel Deployment
              run: |
                  html_validation_failed=$(cat validation_results/html_validation_failed_flag.txt)
                  css_validation_failed=$(cat validation_results/css_validation_failed_flag.txt)
                  pytest_failed=$(cat test_results/test_passed_flag.txt)
                  if [ "$html_validation_failed" -eq 1 ] || [ "$css_validation_failed" -eq 1 ] || [ "$pytest_failed" -eq 1 ]; then
                      echo "Cancelling deployment."
                      exit 1
                  else
                      echo "Deployment proceeding."
                  fi
              