name: Cancel Deployment

on:
    push:
        branches:
            - main
            - gh-pages
            - validation-testing

jobs:
    cancel_deployment:
        runs-on: ubuntu-latest

        steps:
            - name: Poll for dependent workflows completion
              id: poll_workflows
              run: |
                  CHECK_INTERVAL=10
                  MAX_ATTEMPTS=60  # Max wait time: 10 * 60 = 600 seconds (10 minutes)
                  ATTEMPT=0

                  while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
                    ATTEMPT=$((ATTEMPT + 1))

                    # Check the status of the first dependent workflow
                    TESTS_STATUS=$(gh run list --workflow "Automated Tests" --branch main --json status --jq '.[0].status')
                    VALIDATION_STATUS=$(gh run list --workflow "W3C HTML & CSS Validation" --branch main --json status --jq '.[0].status')

                    echo "Automated Tests status: $TESTS_STATUS"
                    echo "W3C HTML & CSS Validation status: $VALIDATION_STATUS"

                    if [[ "$TESTS_STATUS" == "completed" && "$VALIDATION_STATUS" == "completed" ]]; then
                      echo "All dependent workflows are completed."
                      break
                    fi

                    echo "Waiting for workflows to complete..."
                    sleep $CHECK_INTERVAL
                  done

                  if [[ $ATTEMPT -ge $MAX_ATTEMPTS ]]; then
                    echo "Timeout waiting for dependent workflows to complete."
                    exit 1
                  fi
                  echo "All dependent workflows are completed."

            - name: Upload validation results
              uses: actions/upload-artifact@v3
              with:
                  name: w3c-validation-results
                  path: validation_results/

            - name: Cancel Deployment
              run: |
                  html_validation_failed=$(cat validation_results/html_validation_failed_flag
