name: W3C Validation

on:
    push:
        branches:
            - main
            - gh-pages
    pull_request:
        branches:
            - main

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Validate HTML with W3C Validator API
              run: |
                  pip install requests
                  for file in $(find . -name "*.html"); do
                      echo "Validating $file"
                      response=$(curl -s -F "out=json" -F "content=@$file" https://validator.w3.org/nu/?parser=html5)
                      echo "$response"
                    fi
                  done
