name: W3C HTML & CSS Validation

on:
    push:
        branches:
            - main
            - gh-pages
            - validation-testing

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  pip install requests

            - name: Validate HTML with W3C Validator API
              run: |
                  mkdir -p validation_results
                  validation_failed=0
                  for file in $(find . -name "*.html"); do
                      echo "Validating $file"
                      response=$(curl -s -F "out=json" -F "content=@$file" https://validator.w3.org/nu/?parser=html5)
                      output_file="validation_results/w3c-validation-$(basename $file .html).json"
                      echo "$response" > "$output_file"
                      errors=$(echo "$response" | python3 -c "import sys, json; data = json.load(sys.stdin); print(len([msg for msg in data['messages'] if msg['type'] in ['error', 'warning']]))")
                      if [ "$errors" -gt 0 ]; then
                          echo "Validation issues found in $file"
                          validation_failed=1
                      fi
                  done
                  echo "$validation_failed" > validation_results/html_validation_failed_flag.txt

            - name: Validate CSS files
              run: |
                  mkdir -p validation_results
                  validation_failed=0
                  for file in $(find . -name '*.css'); do
                    echo "Validating $file"
                    output_file="validation_results/w3c-validation-$(basename "$file" .css).json"
                    response=$(curl -s -X POST "https://jigsaw.w3.org/css-validator/validator" \
                      -F "file=@$file" \
                      -F "output=json" \
                      -F "profile=css3")
                    echo "$response" > "$output_file"
                    error_count=$(echo "$response" | python3 scripts/validate-css.py)
                    if [ "$error_count" -gt 0 ]; then
                      validation_failed=1
                      echo "Validation failed with $error_count issues in $file"
                    fi
                  done
                  echo "$validation_failed" > validation_results/css_validation_failed_flag.txt

            - name: Upload validation results
              uses: actions/upload-artifact@v3
              with:
                  name: w3c-validation-results
                  path: validation_results/

            - name: Fail if there were validation issues
              run: |
                  html_validation_failed=$(cat validation_results/html_validation_failed_flag.txt)
                  css_validation_failed=$(cat validation_results/css_validation_failed_flag.txt)
                  if [ "$html_validation_failed" -eq 1 ] || [ "$css_validation_failed" -eq 1 ]; then
                    echo "Validation failed due to errors or warnings."
                    exit 1
                  else
                    echo "All files passed validation."
                  fi
